import prisma from '../lib/prisma';
import { sendWhatsAppBill } from '../lib/whatsapp';

// ─── Types ────────────────────────────────────────────────────────────────────
export type ReportSummary = {
  todayRevenue: number;
  todaySalesCount: number;
  totalRecords: number;
  pendingWhatsApp: number;
  avgOrderValue: number;
};

export type DailyReportEntry = {
  date: string;
  revenue: number;
  count: number;
  discount: number;
};

export type PaymentBreakdownEntry = {
  paymentMethod: string;
  revenue: number;
  count: number;
};

// ─── Summary stats ────────────────────────────────────────────────────────────
export async function getReportSummary(): Promise<ReportSummary> {
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const todayEnd = new Date(todayStart.getTime() + 24 * 60 * 60 * 1000);

  const [todaySales, allConfirmedSales, pendingWhatsApp, totalRecords] = await Promise.all([
    prisma.sale.findMany({
      where: { createdAt: { gte: todayStart, lt: todayEnd }, status: 'Confirmed' },
      select: { total: true },
    }),
    prisma.sale.findMany({
      where: { status: 'Confirmed' },
      select: { total: true },
    }),
    prisma.sale.count({
      where: { whatsappStatus: { in: ['Pending', 'Failed'] } },
    }),
    prisma.sale.count(),
  ]);

  const todayRevenue = todaySales.reduce((s, r) => s + r.total, 0);
  const avgOrderValue =
    allConfirmedSales.length > 0
      ? allConfirmedSales.reduce((s, r) => s + r.total, 0) / allConfirmedSales.length
      : 0;

  return {
    todayRevenue: Math.round(todayRevenue),
    todaySalesCount: todaySales.length,
    totalRecords,
    pendingWhatsApp,
    avgOrderValue: Math.round(avgOrderValue),
  };
}

// ─── Daily revenue grouped by date ───────────────────────────────────────────
export async function getDailyReport(days: number): Promise<DailyReportEntry[]> {
  const since = new Date();
  since.setDate(since.getDate() - days);
  since.setHours(0, 0, 0, 0);

  const sales = await prisma.sale.findMany({
    where: { createdAt: { gte: since }, status: 'Confirmed' },
    select: { createdAt: true, total: true, discount: true },
    orderBy: { createdAt: 'asc' },
  });

  const grouped: Record<string, DailyReportEntry> = {};
  for (const sale of sales) {
    const dateStr = sale.createdAt.toISOString().split('T')[0];
    if (!grouped[dateStr]) {
      grouped[dateStr] = { date: dateStr, revenue: 0, count: 0, discount: 0 };
    }
    grouped[dateStr].revenue += sale.total;
    grouped[dateStr].count += 1;
    grouped[dateStr].discount += sale.discount;
  }

  return Object.values(grouped);
}

// ─── Revenue grouped by payment method ───────────────────────────────────────
export async function getPaymentBreakdown(): Promise<PaymentBreakdownEntry[]> {
  const rows = await prisma.sale.groupBy({
    by: ['paymentMethod'],
    where: { status: 'Confirmed' },
    _sum: { total: true },
    _count: { id: true },
  });

  return rows.map((r: { paymentMethod: string; _sum: { total: number | null }; _count: { id: number } }) => ({
    paymentMethod: r.paymentMethod,
    revenue: r._sum.total || 0,
    count: r._count.id,
  }));
}

// ─── Send a daily report via WhatsApp ─────────────────────────────────────────
export interface DailyReportPayload {
  dateLabel: string;
  dateKey: string;
  revenue: number;
  transactions: number;
  piecesSold: number;
  avgOrderValue: number;
  topItem: string;
  paymentBreakdown: Record<string, number>;
  recipientPhone: string;
  recipientName: string;
}

export async function sendDailyReport(
  payload: DailyReportPayload
): Promise<{ success: boolean; error?: string }> {
  const fc = (n: number) => '\u20B9' + n.toLocaleString('en-IN');

  const paymentLines = Object.entries(payload.paymentBreakdown)
    .map(([m, a]) => `• ${m}: ${fc(a)}`)
    .join('\n');

  const body =
    `*ClotheSales — Daily Sales Report*\n` +
    `Date: ${payload.dateLabel}\n\n` +
    `📊 *Summary*\n` +
    `• Revenue: ${fc(payload.revenue)}\n` +
    `• Transactions: ${payload.transactions}\n` +
    `• Pieces Sold: ${payload.piecesSold}\n` +
    `• Avg Order Value: ${fc(payload.avgOrderValue)}\n` +
    `• Top Selling Item: ${payload.topItem}\n\n` +
    `💳 *Payment Breakdown*\n` +
    `${paymentLines}\n\n` +
    `_Generated by ClotheSales_`;

  // Re-use the WhatsApp send utility with a dummy "sale" shape
  return sendWhatsAppBill({
    saleNumber: `RPT-${payload.dateKey}`,
    customerName: payload.recipientName,
    customerPhone: payload.recipientPhone,
    items: [],
    subtotal: payload.revenue,
    discount: 0,
    total: payload.revenue,
    paymentMethod: 'Report',
    createdAt: payload.dateKey,
    _overrideBody: body,
  } as Parameters<typeof sendWhatsAppBill>[0]);
}
